- op: add
  path: /webhooks/0/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
- op: add
  path: /webhooks/1/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
- op: add
  path: /webhooks/3/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
- op: add
  path: /webhooks/4/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
- op: add
  path: /webhooks/5/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
